AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Beats-Bulk-super-admin
  Sample SAM Template for Beats-super-admin

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        region: '{{resolve:ssm:region:1}}' 
        UserPoolId: '{{resolve:ssm:UserPoolId:1}}'
        ClientIdWithSecret: '{{resolve:ssm:ClientIdWithSecret:1}}'
        ClientIdWithSecretSecret: '{{resolve:ssm:ClientIdWithSecretSecret:1}}'
        ClientId: '{{resolve:ssm:ClientId:1}}'
        DefaultPass: '{{resolve:ssm:DefaultPass:1}}'
        S3_BUCKET_NAME: '{{resolve:ssm:S3_BUCKET_NAME:1}}'
        S3_ACCESSKEYID: '{{resolve:ssm:S3_ACCESSKEYID:1}}'
        S3_SECRETACCESSKEY: '{{resolve:ssm:S3_SECRETACCESSKEY:1}}'
        RDS_HOSTNAME: '{{resolve:ssm:RDS_HOSTNAME:1}}'
        RDS_USERNAME: '{{resolve:ssm:RDS_USERNAME:1}}'
        RDS_PASSWORD: '{{resolve:ssm:RDS_PASSWORD:1}}'
        RDS_PORT: '{{resolve:ssm:RDS_PORT:1}}'
        RDS_DATABASE: '{{resolve:ssm:RDS_DATABASE:1}}'
        accessKeyId: '{{resolve:ssm:accessKeyId:1}}'
        secretAccessKey: '{{resolve:ssm:secretAccessKey:1}}'
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,is-update,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
      AllowOrigin: "'*'"
      
Resources:
  BeatsSuperAdminApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: super-admin
      StageName: super-admin
      OpenApiVersion: "2.0"
      Auth:
        Authorizers:
          BeatsUserAuthorizer:
            UserPoolArn: '{{resolve:ssm:UserPoolArn:1}}'
            Identity:
              Header: Authorization
  GatewayPostSubscriberDetailsResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref BeatsSuperAdminApi
  saveAdminUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SuperAdmin/
      Handler: app.saveAdminUsers
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        PostSubscriberApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref BeatsSuperAdminApi
            Path: /saveAdminUsers
            Method: post
            Auth:
              Authorizer: BeatsUserAuthorizer
  fetchAdminUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SuperAdmin/
      Handler: app.fetchAdminUsers
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        PostSubscriberApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref BeatsSuperAdminApi
            Path: /fetchAdminUsers
            Method: get
            Auth:
              Authorizer: BeatsUserAuthorizer