version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beats-bulk-api-signin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qxau92e87iln"
s3_prefix = "beats-bulk-api-signin"
region = "us-east-2"
profile = "beats-bulk-prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
