AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 512 # MB
    
Description: 
  SAM Template for beats group & payer mapping validation

Resources:
  GroupPayerValidationLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: beats-bulk-validation-group-payer-map
      Timeout: 300 # secs
      Description: beats-bulk-validation-group-payer-map
      CodeUri: src
      Handler: validation.lambda_handler
      Events:
        ValidationSQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-2:519922284892:beats-bulk-mapping-sqs-dev
            BatchSize: 1
      Layers:
        - 'arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-pandas:1' 
        - 'arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-PyMySQL:4'
        - 'arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-openpyxl:9'

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonS3FullAccess
        - AWSLambdaSQSQueueExecutionRole

Outputs:

  GroupPayerValidationLambdaFunctionARN:
    Description: "Lambda Function ARN"
    Value: !GetAtt GroupPayerValidationLambdaFunction.Arn

  