AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DockerRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref "AWS::StackName"

Outputs:
  DockerRepo:
    Value: !Ref DockerRepo
    Export:
      Name: !Sub "${AWS::StackName}-DockerRepo"

  DockerRepoUrl:
    Value: !Sub "${AWS::AccountId}.era.ecr.${AWS::Region}.amazonaws.com/${DockerRepo}"
    Export:
      Name: !Sub "${AWS::StackName}-DockerRepoUrl"
